// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>NS</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NS {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class HTTP_POSTS {
        
        private string cHUNK_NRField;
        
        private string cHUNK_SIZEField;
        
        private string nR_RECORDSField;
        
        private List<HTTP_POST> hTTP_POSTField;
        
        public HTTP_POSTS() {
            this.hTTP_POSTField = new List<HTTP_POST>();
        }
        
        public string CHUNK_NR {
            get {
                return this.cHUNK_NRField;
            }
            set {
                this.cHUNK_NRField = value;
            }
        }
        
        public string CHUNK_SIZE {
            get {
                return this.cHUNK_SIZEField;
            }
            set {
                this.cHUNK_SIZEField = value;
            }
        }
        
        public string NR_RECORDS {
            get {
                return this.nR_RECORDSField;
            }
            set {
                this.nR_RECORDSField = value;
            }
        }
        
        public List<HTTP_POST> HTTP_POST {
            get {
                return this.hTTP_POSTField;
            }
            set {
                this.hTTP_POSTField = value;
            }
        }
    }
    
    public partial class HTTP_POST {
        
        private string rECORD_NRField;
        
        private string dEBITEURNUMMERField;
        
        private string dEBITEURNAAMField;
        
        private string dEBITEURVOORLETTERSField;
        
        private string dEBITEURGEBOORTEDATUMField;
        
        private string dEBITEURADRESField;
        
        private string dEBITEURHUISNUMMERField;
        
        private string dEBITEURHUISNUMMERTOEVOEGINGField;
        
        private string dEBITEURPOSTCODEField;
        
        private string dEBITEURPOSTBUSField;
        
        private string dEBITEURPOSTBUSPOSTCODEField;
        
        private string dEBITEURSTADField;
        
        private string dEBITEURLANDField;
        
        private string dEBITEURTELEFOONField;
        
        private string dEBITEURFAXField;
        
        private string dEBITEURGSMField;
        
        private string dEBITEURREKENINGNUMMERField;
        
        private string dEBITEURREKENINGTYPEField;
        
        private string dEBITEUREMAILField;
        
        private HTTP_POSTBEDRIJFPARTICULIER bEDRIJFPARTICULIERField;
        
        private string dEBITEURCONTACTPERSOONField;
        
        private string dEBITEURCONTACTPERSOONGESLACHTField;
        
        private string fACTUURNUMMERField;
        
        private string fACTUURBEDRAGField;
        
        private string fACTUURDATUMField;
        
        private string fACTUURVERVALDATUMField;
        
        private string kENMERKField;
        
        private List<HTTP_POSTORDERREGEL> oRDERREGELField;
        
        private string pROFILEIDField;
        
        private string vALUTAField;
        
        private string cLASSIFYIDField;
        
        private string sTARTDATUMField;
        
        private string cUSTOMER_OPTION1Field;
        
        private string cUSTOMER_OPTION2Field;
        
        private string cUSTOMER_OPTION3Field;
        
        private string cUSTOMER_OPTION4Field;
        
        private string cUSTOMER_OPTION5Field;
        
        private string cUSTOMER_OPTION6Field;
        
        private string cUSTOMER_OPTION7Field;
        
        private string cUSTOMER_OPTION8Field;
        
        private string cUSTOMER_OPTION9Field;
        
        private string cUSTOMER_OPTION10Field;
        
        private string cUSTOMER_OPTION11Field;
        
        private string cUSTOMER_OPTION12Field;
        
        private string cUSTOMER_OPTION13Field;
        
        private string cUSTOMER_OPTION14Field;
        
        private string cUSTOMER_OPTION15Field;
        
        private string cUSTOMER_OPTION16Field;
        
        private string cUSTOMER_OPTION17Field;
        
        private string cUSTOMER_OPTION18Field;
        
        private string cUSTOMER_OPTION19Field;
        
        private string cUSTOMER_OPTION20Field;
        
        private string cUSTOMER_OPTION21Field;
        
        private string cUSTOMER_OPTION22Field;
        
        private string cUSTOMER_OPTION23Field;
        
        private string cUSTOMER_OPTION24Field;
        
        private string cUSTOMER_OPTION25Field;
        
        private string vALUTA_BASISField;
        
        private string oPENSTAANDBEDRAG_BASISField;
        
        private string fACTUURBEDRAG_BASISField;
        
        public HTTP_POST() {
            //this.oRDERREGELField = new List<HTTP_POSTORDERREGEL>();
            //this.bEDRIJFPARTICULIERField = new HTTP_POSTBEDRIJFPARTICULIER();
        }
        
        public string RECORD_NR {
            get {
                return this.rECORD_NRField;
            }
            set {
                this.rECORD_NRField = value;
            }
        }
        
        public string DEBITEURNUMMER {
            get {
                return this.dEBITEURNUMMERField;
            }
            set {
                this.dEBITEURNUMMERField = value;
            }
        }
        
        public string DEBITEURNAAM {
            get {
                return this.dEBITEURNAAMField;
            }
            set {
                this.dEBITEURNAAMField = value;
            }
        }
        
        public string DEBITEURVOORLETTERS {
            get {
                return this.dEBITEURVOORLETTERSField;
            }
            set {
                this.dEBITEURVOORLETTERSField = value;
            }
        }
        
        public string DEBITEURGEBOORTEDATUM {
            get {
                return this.dEBITEURGEBOORTEDATUMField;
            }
            set {
                this.dEBITEURGEBOORTEDATUMField = value;
            }
        }
        
        public string DEBITEURADRES {
            get {
                return this.dEBITEURADRESField;
            }
            set {
                this.dEBITEURADRESField = value;
            }
        }
        
        public string DEBITEURHUISNUMMER {
            get {
                return this.dEBITEURHUISNUMMERField;
            }
            set {
                this.dEBITEURHUISNUMMERField = value;
            }
        }
        
        public string DEBITEURHUISNUMMERTOEVOEGING {
            get {
                return this.dEBITEURHUISNUMMERTOEVOEGINGField;
            }
            set {
                this.dEBITEURHUISNUMMERTOEVOEGINGField = value;
            }
        }
        
        public string DEBITEURPOSTCODE {
            get {
                return this.dEBITEURPOSTCODEField;
            }
            set {
                this.dEBITEURPOSTCODEField = value;
            }
        }
        
        public string DEBITEURPOSTBUS {
            get {
                return this.dEBITEURPOSTBUSField;
            }
            set {
                this.dEBITEURPOSTBUSField = value;
            }
        }
        
        public string DEBITEURPOSTBUSPOSTCODE {
            get {
                return this.dEBITEURPOSTBUSPOSTCODEField;
            }
            set {
                this.dEBITEURPOSTBUSPOSTCODEField = value;
            }
        }
        
        public string DEBITEURSTAD {
            get {
                return this.dEBITEURSTADField;
            }
            set {
                this.dEBITEURSTADField = value;
            }
        }
        
        public string DEBITEURLAND {
            get {
                return this.dEBITEURLANDField;
            }
            set {
                this.dEBITEURLANDField = value;
            }
        }
        
        public string DEBITEURTELEFOON {
            get {
                return this.dEBITEURTELEFOONField;
            }
            set {
                this.dEBITEURTELEFOONField = value;
            }
        }
        
        public string DEBITEURFAX {
            get {
                return this.dEBITEURFAXField;
            }
            set {
                this.dEBITEURFAXField = value;
            }
        }
        
        public string DEBITEURGSM {
            get {
                return this.dEBITEURGSMField;
            }
            set {
                this.dEBITEURGSMField = value;
            }
        }
        
        public string DEBITEURREKENINGNUMMER {
            get {
                return this.dEBITEURREKENINGNUMMERField;
            }
            set {
                this.dEBITEURREKENINGNUMMERField = value;
            }
        }
        
        public string DEBITEURREKENINGTYPE {
            get {
                return this.dEBITEURREKENINGTYPEField;
            }
            set {
                this.dEBITEURREKENINGTYPEField = value;
            }
        }
        
        public string DEBITEUREMAIL {
            get {
                return this.dEBITEUREMAILField;
            }
            set {
                this.dEBITEUREMAILField = value;
            }
        }
        
        public HTTP_POSTBEDRIJFPARTICULIER BEDRIJFPARTICULIER {
            get {
                return this.bEDRIJFPARTICULIERField;
            }
            set {
                this.bEDRIJFPARTICULIERField = value;
            }
        }
        
        public string DEBITEURCONTACTPERSOON {
            get {
                return this.dEBITEURCONTACTPERSOONField;
            }
            set {
                this.dEBITEURCONTACTPERSOONField = value;
            }
        }
        
        public string DEBITEURCONTACTPERSOONGESLACHT {
            get {
                return this.dEBITEURCONTACTPERSOONGESLACHTField;
            }
            set {
                this.dEBITEURCONTACTPERSOONGESLACHTField = value;
            }
        }
        
        public string FACTUURNUMMER {
            get {
                return this.fACTUURNUMMERField;
            }
            set {
                this.fACTUURNUMMERField = value;
            }
        }
        
        public string FACTUURBEDRAG {
            get {
                return this.fACTUURBEDRAGField;
            }
            set {
                this.fACTUURBEDRAGField = value;
            }
        }
        
        public string FACTUURDATUM {
            get {
                return this.fACTUURDATUMField;
            }
            set {
                this.fACTUURDATUMField = value;
            }
        }
        
        public string FACTUURVERVALDATUM {
            get {
                return this.fACTUURVERVALDATUMField;
            }
            set {
                this.fACTUURVERVALDATUMField = value;
            }
        }
        
        public string KENMERK {
            get {
                return this.kENMERKField;
            }
            set {
                this.kENMERKField = value;
            }
        }
        
        public List<HTTP_POSTORDERREGEL> ORDERREGEL {
            get {
                return this.oRDERREGELField;
            }
            set {
                this.oRDERREGELField = value;
            }
        }
        
        public string PROFILEID {
            get {
                return this.pROFILEIDField;
            }
            set {
                this.pROFILEIDField = value;
            }
        }
        
        public string VALUTA {
            get {
                return this.vALUTAField;
            }
            set {
                this.vALUTAField = value;
            }
        }
        
        public string CLASSIFYID {
            get {
                return this.cLASSIFYIDField;
            }
            set {
                this.cLASSIFYIDField = value;
            }
        }
        
        public string STARTDATUM {
            get {
                return this.sTARTDATUMField;
            }
            set {
                this.sTARTDATUMField = value;
            }
        }
        
        public string CUSTOMER_OPTION1 {
            get {
                return this.cUSTOMER_OPTION1Field;
            }
            set {
                this.cUSTOMER_OPTION1Field = value;
            }
        }
        
        public string CUSTOMER_OPTION2 {
            get {
                return this.cUSTOMER_OPTION2Field;
            }
            set {
                this.cUSTOMER_OPTION2Field = value;
            }
        }
        
        public string CUSTOMER_OPTION3 {
            get {
                return this.cUSTOMER_OPTION3Field;
            }
            set {
                this.cUSTOMER_OPTION3Field = value;
            }
        }
        
        public string CUSTOMER_OPTION4 {
            get {
                return this.cUSTOMER_OPTION4Field;
            }
            set {
                this.cUSTOMER_OPTION4Field = value;
            }
        }
        
        public string CUSTOMER_OPTION5 {
            get {
                return this.cUSTOMER_OPTION5Field;
            }
            set {
                this.cUSTOMER_OPTION5Field = value;
            }
        }
        
        public string CUSTOMER_OPTION6 {
            get {
                return this.cUSTOMER_OPTION6Field;
            }
            set {
                this.cUSTOMER_OPTION6Field = value;
            }
        }
        
        public string CUSTOMER_OPTION7 {
            get {
                return this.cUSTOMER_OPTION7Field;
            }
            set {
                this.cUSTOMER_OPTION7Field = value;
            }
        }
        
        public string CUSTOMER_OPTION8 {
            get {
                return this.cUSTOMER_OPTION8Field;
            }
            set {
                this.cUSTOMER_OPTION8Field = value;
            }
        }
        
        public string CUSTOMER_OPTION9 {
            get {
                return this.cUSTOMER_OPTION9Field;
            }
            set {
                this.cUSTOMER_OPTION9Field = value;
            }
        }
        
        public string CUSTOMER_OPTION10 {
            get {
                return this.cUSTOMER_OPTION10Field;
            }
            set {
                this.cUSTOMER_OPTION10Field = value;
            }
        }
        
        public string CUSTOMER_OPTION11 {
            get {
                return this.cUSTOMER_OPTION11Field;
            }
            set {
                this.cUSTOMER_OPTION11Field = value;
            }
        }
        
        public string CUSTOMER_OPTION12 {
            get {
                return this.cUSTOMER_OPTION12Field;
            }
            set {
                this.cUSTOMER_OPTION12Field = value;
            }
        }
        
        public string CUSTOMER_OPTION13 {
            get {
                return this.cUSTOMER_OPTION13Field;
            }
            set {
                this.cUSTOMER_OPTION13Field = value;
            }
        }
        
        public string CUSTOMER_OPTION14 {
            get {
                return this.cUSTOMER_OPTION14Field;
            }
            set {
                this.cUSTOMER_OPTION14Field = value;
            }
        }
        
        public string CUSTOMER_OPTION15 {
            get {
                return this.cUSTOMER_OPTION15Field;
            }
            set {
                this.cUSTOMER_OPTION15Field = value;
            }
        }
        
        public string CUSTOMER_OPTION16 {
            get {
                return this.cUSTOMER_OPTION16Field;
            }
            set {
                this.cUSTOMER_OPTION16Field = value;
            }
        }
        
        public string CUSTOMER_OPTION17 {
            get {
                return this.cUSTOMER_OPTION17Field;
            }
            set {
                this.cUSTOMER_OPTION17Field = value;
            }
        }
        
        public string CUSTOMER_OPTION18 {
            get {
                return this.cUSTOMER_OPTION18Field;
            }
            set {
                this.cUSTOMER_OPTION18Field = value;
            }
        }
        
        public string CUSTOMER_OPTION19 {
            get {
                return this.cUSTOMER_OPTION19Field;
            }
            set {
                this.cUSTOMER_OPTION19Field = value;
            }
        }
        
        public string CUSTOMER_OPTION20 {
            get {
                return this.cUSTOMER_OPTION20Field;
            }
            set {
                this.cUSTOMER_OPTION20Field = value;
            }
        }
        
        public string CUSTOMER_OPTION21 {
            get {
                return this.cUSTOMER_OPTION21Field;
            }
            set {
                this.cUSTOMER_OPTION21Field = value;
            }
        }
        
        public string CUSTOMER_OPTION22 {
            get {
                return this.cUSTOMER_OPTION22Field;
            }
            set {
                this.cUSTOMER_OPTION22Field = value;
            }
        }
        
        public string CUSTOMER_OPTION23 {
            get {
                return this.cUSTOMER_OPTION23Field;
            }
            set {
                this.cUSTOMER_OPTION23Field = value;
            }
        }
        
        public string CUSTOMER_OPTION24 {
            get {
                return this.cUSTOMER_OPTION24Field;
            }
            set {
                this.cUSTOMER_OPTION24Field = value;
            }
        }
        
        public string CUSTOMER_OPTION25 {
            get {
                return this.cUSTOMER_OPTION25Field;
            }
            set {
                this.cUSTOMER_OPTION25Field = value;
            }
        }
        
        public string VALUTA_BASIS {
            get {
                return this.vALUTA_BASISField;
            }
            set {
                this.vALUTA_BASISField = value;
            }
        }
        
        public string OPENSTAANDBEDRAG_BASIS {
            get {
                return this.oPENSTAANDBEDRAG_BASISField;
            }
            set {
                this.oPENSTAANDBEDRAG_BASISField = value;
            }
        }
        
        public string FACTUURBEDRAG_BASIS {
            get {
                return this.fACTUURBEDRAG_BASISField;
            }
            set {
                this.fACTUURBEDRAG_BASISField = value;
            }
        }
    }
    
    public partial class HTTP_POSTBEDRIJFPARTICULIER {
        
        private HTTP_POSTBEDRIJFPARTICULIERType typeField;
        
        public HTTP_POSTBEDRIJFPARTICULIERType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    public enum HTTP_POSTBEDRIJFPARTICULIERType {
        
        /// <remarks/>
        bedrijf,
        
        /// <remarks/>
        particulier,
    }
    
    public partial class HTTP_POSTORDERREGEL {
        
        private string oRDERREGELNUMMERField;
        
        private string oRDERREGELOMSCHRIJVINGField;
        
        private string sTUKSPRIJSField;
        
        private string aANTALField;
        
        private string bTWPERSTUKField;
        
        private string tOTAALREGELBEDRAGField;
        
        private string tOTAALREGELBTWField;
        
        public string ORDERREGELNUMMER {
            get {
                return this.oRDERREGELNUMMERField;
            }
            set {
                this.oRDERREGELNUMMERField = value;
            }
        }
        
        public string ORDERREGELOMSCHRIJVING {
            get {
                return this.oRDERREGELOMSCHRIJVINGField;
            }
            set {
                this.oRDERREGELOMSCHRIJVINGField = value;
            }
        }
        
        public string STUKSPRIJS {
            get {
                return this.sTUKSPRIJSField;
            }
            set {
                this.sTUKSPRIJSField = value;
            }
        }
        
        public string AANTAL {
            get {
                return this.aANTALField;
            }
            set {
                this.aANTALField = value;
            }
        }
        
        public string BTWPERSTUK {
            get {
                return this.bTWPERSTUKField;
            }
            set {
                this.bTWPERSTUKField = value;
            }
        }
        
        public string TOTAALREGELBEDRAG {
            get {
                return this.tOTAALREGELBEDRAGField;
            }
            set {
                this.tOTAALREGELBEDRAGField = value;
            }
        }
        
        public string TOTAALREGELBTW {
            get {
                return this.tOTAALREGELBTWField;
            }
            set {
                this.tOTAALREGELBTWField = value;
            }
        }
    }
}
