var URL_LISTENER = "https://forms.netsuite.com/app/site/hosting/scriptlet.nl?script=2&deploy=1&compid=3337767&h=7320894c5b96e9beb613";
var URL_IMAGES = "https://www.infinetcloud.com/images/app/";

var PAYROLL_COUNTRY_NZ = '1';
var PAYROLL_COUNTRY_AU = '2';
var PAYROLL_COUNTRY_UK = '3';
var PAYROLL_COUNTRY_LIBERIA = '4';

//var PAYROLL_COUNTRY = PAYROLL_COUNTRY_AU;

var PAYRUN_TYPE_STANDARD = '1';
var PAYRUN_TYPE_ADJUSTMENT = '2';
var PAYRUN_TYPE_ONEOFF = '3';
var PAYRUN_TYPE_TERMINATION = '4';
var PAYRUN_TYPE_REDUNDANCY = '5';
var PAYRUN_TYPE_BONUS = '6';
var PAYRUN_TYPE_REIMBURSEMENT = '7';

var PAY_COMPONENT_TYPE_SALARY_WAGES= '1';
var PAY_COMPONENT_TYPE_ALLOWANCE = '2';
var PAY_COMPONENT_TYPE_DEDUCTION = '3';
var PAY_COMPONENT_TYPE_LEAVE = '4';
var PAY_COMPONENT_TYPE_TAX = '5';
var PAY_COMPONENT_TYPE_SUPER = '6';
var PAY_COMPONENT_TYPE_EXPENSES = '7';
var PAY_COMPONENT_TYPE_SALARY_SACRIFICE = '8';
var PAY_COMPONENT_TYPE_EMPTY = '9';
var PAY_COMPONENT_TYPE_NI = '11';
var PAY_COMPONENT_TYPE_PENSIONS = '12';

var PAY_COMPONENT_CATEGORY_NORMAL_TIME = '1';
var PAY_COMPONENT_CATEGORY_OVER_TIME = '2';
var PAY_COMPONENT_CATEGORY_PENALTY_RATE = '3';
var PAY_COMPONENT_CATEGORY_PAID_LEAVE = '4';
var PAY_COMPONENT_CATEGORY_UNPAID_LEAVE = '5';
var PAY_COMPONENT_CATEGORY_EMPTY = '6';
var PAY_COMPONENT_CATEGORY_EMPTY = '7';
var PAY_COMPONENT_CATEGORY_EMPTY = '8';
var PAY_COMPONENT_CATEGORY_WORKING_CONDITIONS = '9';
var PAY_COMPONENT_CATEGORY_QUALIFICATIONS = '10';
var PAY_COMPONENT_CATEGORY_NON_DEDUCTABLE_EXPENSES = '11';
var PAY_COMPONENT_CATEGORY_DEDUCTABLE_EXPENSES = '12';
var PAY_COMPONENT_CATEGORY_SUPERANNUATION = '13';
var PAY_COMPONENT_CATEGORY_DEDUCTION = '14';
var PAY_COMPONENT_CATEGORY_REIMBURSABLE_EXPENSES = '15';
var PAY_COMPONENT_CATEGORY_TAXATION = '16';
var PAY_COMPONENT_CATEGORY_BONUS = '17';
var PAY_COMPONENT_CATEGORY_COMMISSION = '18';
var PAY_COMPONENT_CATEGORY_SALARY_SACRIFICE = '19';
var PAY_COMPONENT_CATEGORY_TIME_IN_LIEU = '20';
var PAY_COMPONENT_CATEGORY_LEAVE_LOADING = '21';
var PAY_COMPONENT_CATEGORY_EMPTY = '22';
var PAY_COMPONENT_CATEGORY_EMPTY = '23';
var PAY_COMPONENT_CATEGORY_EXTRA_SUPER = '24';
var PAY_COMPONENT_CATEGORY_UNUSED_LEAVE = '26';
var PAY_COMPONENT_CATEGORY_TAX_CREDIT = '29';
var PAY_COMPONENT_CATEGORY_EMPLOYEE_NI = '30';
var PAY_COMPONENT_CATEGORY_EMPLOYER_NI = '31';
var PAY_COMPONENT_CATEGORY_EMPLOYER_PENSION = '32';
var PAY_COMPONENT_CATEGORY_EMPLOYEE_PENSION = '33';
var PAY_COMPONENT_CATEGORY_EMPLOYER_KIWI = '34';
var PAY_COMPONENT_CATEGORY_LEAVE_ACCRUAL = 35;

var netSuiteTypeMappingObj = {};
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SALARY_WAGES] = "earning";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_ALLOWANCE] = "earning";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_DEDUCTION] = "deduction";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_TAX] = "employeetax";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SUPER] = "companycontribution";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_EXPENSES] = "earning";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SALARY_SACRIFICE] = "deduction";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_NI] = {};
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_NI][PAY_COMPONENT_CATEGORY_EMPLOYER_NI] = "companycontribution";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_NI][PAY_COMPONENT_CATEGORY_EMPLOYEE_NI] = "employeetax";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SALARY_SACRIFICE] = {};
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SALARY_SACRIFICE][PAY_COMPONENT_CATEGORY_EMPLOYER_PENSION] = "companycontribution";
netSuiteTypeMappingObj[PAY_COMPONENT_TYPE_SALARY_SACRIFICE][PAY_COMPONENT_CATEGORY_EMPLOYEE_PENSION] = "deduction";

// depreceated no longer in use.
var TEMPLATE_PAYSLIP_PDF = "2";
var TEMPLATE_PAYSLIP_HTML = "4";

var TEMPLATE_TYPE_PAYSLIP = "1";
var TEMPLATE_TYPE_PAYSUMMARY = "2";
var TEMPLATE_TYPE_EMAIL = "3";
var TEMPLATE_TYPE_INTERNAL = "4";

var PAY_DOCUMENT_PAYSLIP = "1";
var PAY_DOCUMENT_PAYSUMMARY = "3";

var ACCRUAL_TYPE_ACCRUAL = '1';
var ACCRUAL_TYPE_TAKEN = '2';

var PAYROLL_ACTION_TIMESHEET = '1';
var PAYROLL_ACTION_CREATE_PAYSLIPS = '5';
var PAYROLL_ACTION_APPROVE = '6';
var PAYROLL_ACTION_POST = '7';
var PAYROLL_ACTION_START_PAYRUN = '8';
var PAYROLL_ACTION_SET_VARIABLES = '9';
var PAYROLL_ACTION_POSTED = '10';
var PAYROLL_ACTION_PAID = '11';
var PAYROLL_ACTION_ROLLBACK = '12';
var PAYROLL_ACTION_ABA = '13';
var PAYROLL_ACTION_EMAILED = '14';
var PAYROLL_ACTION_CREATE_ONEOFF = '15';
var PAYROLL_ACTION_LOGGED = '16';
var PAYROLL_ACTION_RECALC_ALL = '17';
var PAYROLL_ACTION_RECALC_TOTALS = '18';
var PAYROLL_ACTION_PRINT_PAYSLIPS = '19';

var PAYRUN_STATUS_STARTED = '1';
var PAYRUN_STATUS_TIME_ENTERED = '2';
var PAYRUN_STATUS_TIME_PENDING = '3';
var PAYRUN_STATUS_PAYSLIPS_CREATED = '4';
var PAYRUN_STATUS_PAYSLIPS_APPROVED = '5';
var PAYRUN_STATUS_PAYSLIPS_PARTIALLY_APPROVED = '6';
var PAYRUN_STATUS_POSTED = '7';
var PAYRUN_STATUS_PARTIALLY_POSTED = '8';
var PAYRUN_STATUS_PAID = '9';
var PAYRUN_STATUS_PARTIALLY_PAID = '10';
var PAYRUN_STATUS_POSTING_SCHEDULED = '11';
var PAYRUN_STATUS_VARIABLES = '12';
var PAYRUN_STATUS_EMAILED = '13';
var PAYRUN_STATUS_PAYMENT_SCHEDULED = '14';
var PAYRUN_STATUS_AUTOPAY_VARIABLE = '24';
var PAYRUN_STATUS_AUTOPAY_PROCESS = '25';
var PAYRUN_STATUS_AUTOPAY_APPROVAL = '15';
var PAYRUN_STATUS_AUTOPAY_POSTED = '16';
var PAYRUN_STATUS_AUTOPAY_PAYMENT = '17';
var PAYRUN_STATUS_ERROR = '18';
var PAYRUN_STATUS_ROLLBACK = '19';
var PAYRUN_STATUS_SCHEDULED_START = '20';
var PAYRUN_STATUS_SCHEDULED_TIME = '21';
var PAYRUN_STATUS_SCHEDULED_VARIABLE = '22';
var PAYRUN_STATUS_SCHEDULED_EMAIL = '23';

var STEP_APPROVAL = '1';
var STEP_POSTING = '2';
var STEP_PAYMENT = '3';
var STEP_START = '4';
var STEP_TIME = '5';
var STEP_VARIABLE = '6';
var STEP_PROCESS = '7';
var STEP_EMAIL = '8';
var STEP_ONEOFF = '9';
var STEP_MANUAL = '10';


var PAYROLL_SUCCESS = '1';
var PAYROLL_FAILURE = '2';

var PAYANNUAL = '1';
var PAYBIANNUAL = '2';
var PAYBIWEEKLY = '3';
var PAYMONTHLY = '4';
var PAYFOURWEEKLY = '5';
var PAYQUARTERLY = '6';
var PAYWEEKLY = '7';
var PAYEXCLUDE = '8';
var PAYSEMIMONTHLY = '9';

var PAYSLIP_PENDING_APPROVAL = '1';
var PAYSLIP_APPROVED = '2';
var PAYSLIP_POSTED = '3';
var PAYSLIP_PAID = '4';
var PAYSLIP_PAYRUN_STARTED = '5';
var PAYSLIP_PAYRUN_ERROR = '6';
var PAYSLIP_EMAILED = '7';

var PAYRUN_MONTHLY_LASTDAYOFMONTH = '32';
var PAYRUN_MONTHLY_LASTBUSINESSDAYOFMONTH = '33';

var EMP_PAY_TYPE_SALARY = '1';
var EMP_PAY_TYPE_WAGES = '2';

var PAYROLL_UOM_HOUR = '1';
var PAYROLL_UOM_PAY_PERIOD = '2';
var PAYROLL_UOM_KILOMETRE = '3';
var PAYROLL_UOM_DAY= '4';
var PAYROLL_UOM_WEEK = '5';
var PAYROLL_UOM_MONTH = '6';
var PAYROLL_UOM_YEAR = '7';
var PAYROLL_UOM_LUMP = '8';
var PAYROLL_UOM_FORTNIGHTLY = '9';
var PAYROLL_UOM_QUARTERLY = '10';
var PAYROLL_UOM_FOURWEEKLY = '11';
var PAYROLL_UOM_SEMIMONTH = '16';

var EMPLOYEE_EMPLOYMENT_STATUS_FULLTIME = '1';
var EMPLOYEE_EMPLOYMENT_STATUS_PARTTIME = '2';
var EMPLOYEE_EMPLOYMENT_STATUS_CASUAL = '3';
var EMPLOYEE_EMPLOYMENT_STATUS_CONTRACT = '4';
var EMPLOYEE_EMPLOYMENT_STATUS_DIRECTOR = '5';
var EMPLOYEE_EMPLOYMENT_STATUS_TERMINATED = '6';

var EMPLOYEE_IS_RESIDENT = "1";
var EMPLOYEE_IS_NON_RESIDENT = "2";

var PAYSLIP_DELIVERY_EMAIL = "2";

var PERCENTAGE_TYPE_SALARY_SACRIFICE = '1';
var PERCENTAGE_TYPE_AFTERTAX = '2';
var PERCENTAGE_TYPE_GROSS_PAY = '3';
var PERCENTAGE_TYPE_NONE = '4';
var PERCENTAGE_TYPE_TAXABLE_INCOME = '5';
var PERCENTAGE_TYPE_BASE_FOR_SUPER = '6';
var PERCENTAGE_TYPE_BASE_FOR_PENSION = '7';
var PERCENTAGE_TYPE_BASE_FOR_NI = '8';

var VENDORTYPE_TAXAGENCY = "3";

var ENTITY_RECORD_STATUS_PRIMARY = '1';
var ENTITY_RECORD_STATUS_SECONDARY = '2';

var FOLDER_ATTACH_RECEIVED = "-10";
var FOLDER_ATTACH_SEND = "-14"; 

var FEATURE_BIT_AUTOPAY = 1;
var FEATURE_BIT_LEAVE = 2;
var FEATURE_BIT_TIME = 16;
var FEATURE_BIT_BASIC = 32;

var SETUP_MAX_EMPLOYEE = 20;
var SETUP_MAX_VENDOR = 20;

var TERMINATION_NORMAL = '1';
var TERMINATION_GENUINE_REDUNDANCY = '2';
var TERMINATION_INVALIDITY = '3';
var TERMINATION_EARLY_RETIREMENT = '4';

var LEAVEREQ_STATUS_PENDING = '1';
var LEAVEREQ_STATUS_APPROVED = '2';
var LEAVEREQ_STATUS_DECLINED = '3';
var LEAVEREQ_STATUS_CANCELLED = '4';
var LEAVEREQ_STATUS_PROCESSED = '5';
var LEAVEREQ_STATUS_MANUAL = '6';
var LEAVETIME_PROCESSMAX = 60;

var LEAVE_AVAILABLE_ASACCRUED = '1';
var LEAVE_AVAILABLE_ASANNIVERSARY = '2';

var LEAVE_AVAILABLE_CALC_EXCFUTURE = '1';
var LEAVE_AVAILABLE_CALC_INCFUTURE = '2';

var LEAVE_BLOCK_MAX = 20;

var LEAVEBLK_STATUS_SCHEDULED_CREATE = "1";
var LEAVEBLK_STATUS_PROCESSING = "2";
var LEAVEBLK_STATUS_COMPLETE = "3";
var LEAVEBLK_STATUS_ERROR = "4";
var LEAVEBLK_STATUS_SCHEDULED_DELETE = "5";

var ROLE_ADMINISTRATOR = '3';


var ANNUAL_LEAVE_ENTITLEMENT_NONE = '10';
var PERSONAL_LEAVE_ENTITLEMENT_NONE = '11';
var LSL_LEAVE_ENTITLEMENT_NONE = '12';

var PAY_METHOD_EFT = '1';
var PAY_METHOD_CHEQUE = '2';
var PAY_METHOD_CASH = '3';

var UPDATE_PAYSLIP_BALANCE = '1';
var UPDATE_PAYSLIP_OVERTIME = '2';
var UPDATE_PAYSLIP_EMP_SUPER = '3';

var PART_PERIOD_METHOD_WORKING_HOURS = '1';
var PART_PERIOD_METHOD_WORKING_DAYS = '2';
var PART_PERIOD_METHOD_DAYS_IN_PERIOD = '3';

var SUMMARY_LOCATION_GROSSPAYMENT = "1";
var SUMMARY_LOCATION_ALLOWANCES = "2";
var SUMMARY_LOCATION_NONREPORTABLE = "3";
var SUMMARY_LOCATION_REPORTABLEFBT = "4";
var SUMMARY_LOCATION_LUMPSUMA = "5";
var SUMMARY_LOCATION_LUMPSUMB = "6";
var SUMMARY_LOCATION_LUMPSUMC = "7";
var SUMMARY_LOCATION_LUMPSUMD = "8";
var SUMMARY_LOCATION_LUMPSUME = "9";
var SUMMARY_LOCATION_UNIONFEES = "10";
var SUMMARY_LOCATION_CDEP = "11";
var SUMMARY_LOCATION_RESC = "12";
var SUMMARY_LOCATION_TAXWITHHELD = "13";
var SUMMARY_LOCATION_WORKPLACEGIVING = "14";
var SUMMARY_LOCATION_ETP = "15";
var SUMMARY_LOCATION_ETPTAXFREE = "16";
var SUMMARY_LOCATION_ETPTAXWITHHELD = "17";
var SUMMARY_LOCATION_TAXCREDITDONATIONS = "18";
var SUMMARY_LOCATION_GROSSEARNING = "19";
var SUMMARY_LOCATION_EARNINGACCEXEMPT = "20";
var SUMMARY_LOCATION_PAYETAX = "21";
var SUMMARY_LOCATION_CHILDSUPPORT = "22";
var SUMMARY_LOCATION_STUDENTLOAN = "23";
var SUMMARY_LOCATION_KIWISAVER = "24";
var SUMMARY_LOCATION_KIWISAVEREMPLOYER = "25";
var SUMMARY_LOCATION_TAXCREDITFAMILY = "26";
var SUMMARY_LOCATION_NOTREPORTABLE_NZ = "27";
var SUMMARY_LOCATION_ECST = "28";

var TAX_CODE_NZ_M = '36';
var TAX_CODE_NZ_MSL = '41';
var TAX_CODE_NZ_ME = '38';
var TAX_CODE_NZ_MESL = '42';
var TAX_CODE_NZ_ML = '37';
var TAX_CODE_NZ_MLSL = '80';
var TAX_CODE_NZ_SLBOR = '84';
var TAX_CODE_NZ_SLCIR = '83';
var TAX_CODE_NZ_STC = '44';
var TAX_CODE_NZ_S = '40';
var TAX_CODE_NZ_SB = '78';
var TAX_CODE_NZ_SBSL = '82';
var TAX_CODE_NZ_SSL = '45';
var TAX_CODE_NZ_SH = '74';
var TAX_CODE_NZ_SHSL = '76';
var TAX_CODE_NZ_ST = '75';
var TAX_CODE_NZ_STSL = '77';
var TAX_CODE_NZ_ND = '43';
var TAX_CODE_NZ_CAE = '81';
var TAX_CODE_NZ_WT = '73';
var TAX_CODE_NZ_NSW = '39';

var NZ_REPORT_IR348 = "1";
var NZ_REPORT_IR345 = "2";
var NZ_REPORT_KED = "3";
var NZ_REPORT_DETAIL_MAX = 50;
var NZ_SUMMARY_STATUS_SCHEDULED = "1";
var NZ_SUMMARY_STATUS_PROCESSING = "2";
var NZ_SUMMARY_STATUS_COMPLETE = "3";
var NZ_SUMMARY_STATUS_DATAERROR = "4";
var NZ_SUMMARY_STATUS_FILEERROR = "5";

var ANNUAL_LEAVE_UOM_HOURS = '1';
var ANNUAL_LEAVE_UOM_DAYS = '2';

var ctxObj = nlapiGetContext();
var companyId = ctxObj.getCompany();

var defaultPrecision = 5;
var roundingMethod = 'up';

var taxYear2012 = '5';
var taxYear2013 = '6';

var ECST_SALARY_WAGES = "1";
var ECST_PERSONAL_TAX_RATE = "2";

var PAYRATE_TAXYEAR = "1";
var PAYRATE_EMPLOYEE = "2";
var PAYRATE_GLOBAL = "3";

var ACCRUAL_METHOD_LUMP = "1";
var ACCRUAL_METHOD_PAYRUN = "2";
var ACCRUAL_METHOD_PERIOD = "3";

var HMRC_FORM_P45 = '1';
var HMRC_FORM_P46 = '2';
var HMRC_FORM_P46EXPAT = '3';

var KIWISAVER_OPTIN = '1';
var KIWISAVER_EXISTING = '2';
var KIWISAVER_AUTOENROL = '3';
var KIWISAVER_NOT_ELIGIBLE = '4';

function isNullOrEmpty(valueStr)
{
	return(valueStr == null || valueStr == "" || valueStr == undefined);	
}






