//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.netsuite.com/services/NetSuitePort_2012_1")]
        public string NS_com_netsuite_webservices_NetSuiteService {
            get {
                return ((string)(this["NS_com_netsuite_webservices_NetSuiteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sandbox.netsuite.com/services/NetSuitePort_2012_1")]
        public string NS_com_netsuite_sandbox_webservices_NetSuiteService {
            get {
                return ((string)(this["NS_com_netsuite_sandbox_webservices_NetSuiteService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("customsearch_maxcredibleinvoiceexport_v1")]
        public string NS_MaxCredible_Savedsearch {
            get {
                return ((string)(this["NS_MaxCredible_Savedsearch"]));
            }
            set {
                this["NS_MaxCredible_Savedsearch"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://secure2.maxcredible.com/webservices_alg/invoer_MC.asmx")]
        public string NS_com_maxcredible_www_Invoer_mc {
            get {
                return ((string)(this["NS_com_maxcredible_www_Invoer_mc"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3524453")]
        public string NS_AccountID {
            get {
                return ((string)(this["NS_AccountID"]));
            }
            set {
                this["NS_AccountID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blipeu@aligntech.com")]
        public string NS_UserEmail {
            get {
                return ((string)(this["NS_UserEmail"]));
            }
            set {
                this["NS_UserEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("netsuite1")]
        public string NS_Password {
            get {
                return ((string)(this["NS_Password"]));
            }
            set {
                this["NS_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string NS_Role {
            get {
                return ((string)(this["NS_Role"]));
            }
            set {
                this["NS_Role"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MaxCredibleAlignBV.cer")]
        public string MC_CertificateFile {
            get {
                return ((string)(this["MC_CertificateFile"]));
            }
            set {
                this["MC_CertificateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MCXML\\")]
        public string MC_XMLOutputDir {
            get {
                return ((string)(this["MC_XMLOutputDir"]));
            }
            set {
                this["MC_XMLOutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoicesChunkEUR_")]
        public string MC_XMLOutputPrefix {
            get {
                return ((string)(this["MC_XMLOutputPrefix"]));
            }
            set {
                this["MC_XMLOutputPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MC_DefaultCharLimit {
            get {
                return ((int)(this["MC_DefaultCharLimit"]));
            }
            set {
                this["MC_DefaultCharLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public string MC_DefaultProfileID {
            get {
                return ((string)(this["MC_DefaultProfileID"]));
            }
            set {
                this["MC_DefaultProfileID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MC_DefaultClassifyID {
            get {
                return ((string)(this["MC_DefaultClassifyID"]));
            }
            set {
                this["MC_DefaultClassifyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public string MC_CurrencyExtensionsID {
            get {
                return ((string)(this["MC_CurrencyExtensionsID"]));
            }
            set {
                this["MC_CurrencyExtensionsID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUR")]
        public string MC_BaseCurrency {
            get {
                return ((string)(this["MC_BaseCurrency"]));
            }
            set {
                this["MC_BaseCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MC_CurrencySymbolsMax {
            get {
                return ((int)(this["MC_CurrencySymbolsMax"]));
            }
            set {
                this["MC_CurrencySymbolsMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_AutoSearch {
            get {
                return ((bool)(this["APP_AutoSearch"]));
            }
            set {
                this["APP_AutoSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_AutoUpload {
            get {
                return ((bool)(this["APP_AutoUpload"]));
            }
            set {
                this["APP_AutoUpload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_AutoFinish {
            get {
                return ((bool)(this["APP_AutoFinish"]));
            }
            set {
                this["APP_AutoFinish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-28")]
        public double APP_DefaultDateRange {
            get {
                return ((double)(this["APP_DefaultDateRange"]));
            }
            set {
                this["APP_DefaultDateRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MC_DefaultChunkSize {
            get {
                return ((int)(this["MC_DefaultChunkSize"]));
            }
            set {
                this["MC_DefaultChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webservice349")]
        public string MC_UserName {
            get {
                return ((string)(this["MC_UserName"]));
            }
            set {
                this["MC_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GVRE4MXF")]
        public string MC_Password {
            get {
                return ((string)(this["MC_Password"]));
            }
            set {
                this["MC_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_XMLFileOnly {
            get {
                return ((bool)(this["APP_XMLFileOnly"]));
            }
            set {
                this["APP_XMLFileOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MC_EXPORT.LOG")]
        public string APP_LogFileName {
            get {
                return ((string)(this["APP_LogFileName"]));
            }
            set {
                this["APP_LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://secure6.maxcredible.com/webservices_alg_staging/invoer_MC.asmx")]
        public string MaxCredibleExport_com_maxcredible_secure6_Invoer_mc {
            get {
                return ((string)(this["MaxCredibleExport_com_maxcredible_secure6_Invoer_mc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://secure5.maxcredible.com/webservices_alg/invoer_MC.asmx")]
        public string MaxCredibleExport_com_maxcredible_secure5_Invoer_mc {
            get {
                return ((string)(this["MaxCredibleExport_com_maxcredible_secure5_Invoer_mc"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Central European Standard Time")]
        public string APP_LogTimeZoneCultureInfo {
            get {
                return ((string)(this["APP_LogTimeZoneCultureInfo"]));
            }
            set {
                this["APP_LogTimeZoneCultureInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APP_LogDateStamped {
            get {
                return ((bool)(this["APP_LogDateStamped"]));
            }
            set {
                this["APP_LogDateStamped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double APP_DefaultDateOffset {
            get {
                return ((double)(this["APP_DefaultDateOffset"]));
            }
            set {
                this["APP_DefaultDateOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_UseLiveWebServices {
            get {
                return ((bool)(this["APP_UseLiveWebServices"]));
            }
            set {
                this["APP_UseLiveWebServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APP_LogCanDelete {
            get {
                return ((bool)(this["APP_LogCanDelete"]));
            }
            set {
                this["APP_LogCanDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APP_LogEnabled {
            get {
                return ((bool)(this["APP_LogEnabled"]));
            }
            set {
                this["APP_LogEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_EmailSMTPServer {
            get {
                return ((string)(this["APP_EmailSMTPServer"]));
            }
            set {
                this["APP_EmailSMTPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_EmailSMTPUser {
            get {
                return ((string)(this["APP_EmailSMTPUser"]));
            }
            set {
                this["APP_EmailSMTPUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_EmailSMTPPassword {
            get {
                return ((string)(this["APP_EmailSMTPPassword"]));
            }
            set {
                this["APP_EmailSMTPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_EmailToAddress {
            get {
                return ((string)(this["APP_EmailToAddress"]));
            }
            set {
                this["APP_EmailToAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_EmailCcAddress {
            get {
                return ((string)(this["APP_EmailCcAddress"]));
            }
            set {
                this["APP_EmailCcAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_DatesEnabled {
            get {
                return ((bool)(this["APP_DatesEnabled"]));
            }
            set {
                this["APP_DatesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_WindowsEventLogEnabled {
            get {
                return ((bool)(this["APP_WindowsEventLogEnabled"]));
            }
            set {
                this["APP_WindowsEventLogEnabled"] = value;
            }
        }
    }
}
