// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.7.1
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery;var d=e("ul",b);var f={position:"absolute",left:0,top:0,width:"100%",height:"100%"};this.go=function(g,h){var i=e(a.get(g)).clone().css(f).hide().appendTo(b);if(!c.noCross){var j=e(a.get(h)).clone().css(f).appendTo(b);d.hide();j.fadeOut(c.duration,function(){j.remove()})}i.fadeIn(c.duration,function(){d.css({left:-g+"00%"}).show();i.remove()});return g}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.7.1
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:20*100,delay:40*100,width:918,height:280,autoPlay:true,stopOnHover:true,loop:false,bullets:true,caption:false,captionEffect:"slide",controls:false,logo:"engine1/loading.gif",onBeforeStep:0,images:[{src:"./newhomeofferbluebelle.jpg",title:"",descr:"Order 5 packs or more of seed potatoes and receive 10 tubers of Potato Blue Belle ABSOLUTELY FREE! (while stocks last)",href:"/Potatoes/",target:"_parent"},{src:"./homepage_vegetableplants.jpg",title:"",descr:"Tasty amd nutricious vegetable plants!",href:"/Vegetable-Plants/",target:"_parent"},{src:"./homepage_picnmix.jpg",title:"",descr:"BIG SAVINGS on Mr F's Pick 'n' Mix Bedding Plants",href:"/Flower-Plants/",target:"_parent"},{src:"./homepage_sweetpea.jpg",title:"",descr:"Mr Fothergill's Year of the Sweet Pea!",href:"/Flower-Plants/Sweet-Pea-Plants/",target:"_parent"}]});